### ISSUE TITLE
Is it possible to setup database version ?

### ISSUE THREAD

**Issue by pasankgdigitas** [pantheon-systems/quicksilver-examples#172]
Is there an attribute that I can use to set the database version ?
ex:

database:
  version: 10.4

Thanks

**Comment by greg-1-anderson** [comment]
This question is out of scope for this repository, but I will answer it.

Yes, the attribute for the database may be set in pantheon.yml. See an example here:

https://github.com/pantheon-upstreams/drupal-project/blob/master/pantheon.upstream.yml#L6,L7

However, at the moment, the new database is in Limited Availability, which means that you cannot select 10.4 on an existing site. In order to get MariaDB 10.4, you must start a new site per the Drupal 9 documentation:

https://pantheon.io/docs/drupal-9

Once you have a new Drupal 9 site, you may downgrade it to Drupal 8 if you wish.

A date for General Availability for Mariadb 10.4 has not been announced.

**Comment by pasankgdigitas** [comment]
Thank you very much @greg-1-anderson 
Apologies for adding an out of scope question.
