### ISSUE TITLE
Example wanted: JIRA ticket integration

### ISSUE THREAD

**Issue by joshkoenig** [pantheon-systems/quicksilver-examples#26]
This would make a lot of sense, and we can do it with the `deploy` workflow. There's an existing PHP project to integrate GitLab that we might be able to borrow some API code from:

https://github.com/lesstif/gitlab-jira-integration

**Comment by mikemilano** [comment]
For Jira integration, I was thinking it would have been slick to integrate with the `source` tab of an issue like Atlassian's Fisheye integrates, but the Jira API doesn't support that.  Their workflow would be something done on the `sync_code` event though.

As an alternative, comments could be written when commits are made with an issue id exists in the commit message. I used this idea to get a handle on how the system works. I was successful since I could `shell_exec` git commands from the qs script.

The script writes the latest commit to a file, then the next time code is pushed, it looks through all commits since the commit id saved in the file. It only watches the dev branch.

I'm sure it's not bullet proof because of the nature of git, but I think it would catch most commits... git data in Jira issues isn't extremely critical but it might be nice to automatically see when commits are made against an issue.

Here's a screenshot of a comment: 
<img width="640" alt="jira-integration" src="https://cloud.githubusercontent.com/assets/1287855/12535478/ba797c80-c239-11e5-8803-849ffa0957ff.png">
